export const shipping = [
  {
    "productId": "1",
    "productName": "Tee Model 1",
    "variantId": "1-M",
    "size": "M",
    "color": "White",
    "category": "Tees",
    "status": "Out for delivery",
    "expectedDelivery": "2025-01-21",
    "location": "Mumbai",
    "trackingNumber": "TRK123456789",
    "shippingMethod": "Express Delivery",
    "orderDate": "2025-01-18",
    "price": 1199
  },
  {
    "productId": "2",
    "productName": "Pant Model 2",
    "variantId": "2-32",
    "size": "32",
    "color": "Black",
    "category": "Pants",
    "status": "Will be delivered today",
    "expectedDelivery": "2025-01-21",
    "location": "Delhi",
    "trackingNumber": "TRK987654321",
    "shippingMethod": "Standard Delivery",
    "orderDate": "2025-01-19",
    "price": 1399
  },
  {
    "productId": "3",
    "productName": "Jean Model 3",
    "variantId": "3-30",
    "size": "30",
    "color": "Blue",
    "category": "Jeans",
    "status": "In transit",
    "expectedDelivery": "2025-01-22",
    "location": "Bangalore",
    "trackingNumber": "TRK456789123",
    "shippingMethod": "Express Delivery",
    "orderDate": "2025-01-20",
    "price": 1599
  },
  {
    "productId": "4",
    "productName": "Shirt Model 4",
    "variantId": "4-L",
    "size": "L",
    "color": "White",
    "category": "Shirts",
    "status": "Order confirmed",
    "expectedDelivery": "2025-01-24",
    "location": "Chennai",
    "trackingNumber": "TRK789123456",
    "shippingMethod": "Standard Delivery",
    "orderDate": "2025-01-21",
    "price": 1799
  },
  {
    "productId": "5",
    "productName": "Tee Model 5",
    "variantId": "5-S",
    "size": "S",
    "color": "Blue",
    "category": "Tees",
    "status": "Shipped",
    "expectedDelivery": "2025-01-23",
    "location": "Kolkata",
    "trackingNumber": "TRK321654987",
    "shippingMethod": "Express Delivery",
    "orderDate": "2025-01-20",
    "price": 999
  },
  {
    "productId": "6",
    "productName": "Pant Model 6",
    "variantId": "6-34",
    "size": "34",
    "color": "Gray",
    "category": "Pants",
    "status": "Out for delivery",
    "expectedDelivery": "2025-01-21",
    "location": "Hyderabad",
    "trackingNumber": "TRK147258369",
    "shippingMethod": "Standard Delivery",
    "orderDate": "2025-01-18",
    "price": 1199
  },
  {
    "productId": "7",
    "productName": "Jean Model 7",
    "variantId": "7-32",
    "size": "32",
    "color": "Light Blue",
    "category": "Jeans",
    "status": "In transit",
    "expectedDelivery": "2025-01-22",
    "location": "Pune",
    "trackingNumber": "TRK963852741",
    "shippingMethod": "Express Delivery",
    "orderDate": "2025-01-19",
    "price": 1399
  },
  {
    "productId": "8",
    "productName": "Shirt Model 8",
    "variantId": "8-M",
    "size": "M",
    "color": "Blue",
    "category": "Shirts",
    "status": "Order confirmed",
    "expectedDelivery": "2025-01-25",
    "location": "Ahmedabad",
    "trackingNumber": "TRK852963741",
    "shippingMethod": "Standard Delivery",
    "orderDate": "2025-01-21",
    "price": 1599
  },
  {
    "productId": "9",
    "productName": "Tee Model 9",
    "variantId": "9-L",
    "size": "L",
    "color": "Gray",
    "category": "Tees",
    "status": "Shipped",
    "expectedDelivery": "2025-01-23",
    "location": "Jaipur",
    "trackingNumber": "TRK741852963",
    "shippingMethod": "Express Delivery",
    "orderDate": "2025-01-20",
    "price": 1799
  },
  {
    "productId": "10",
    "productName": "Pant Model 10",
    "variantId": "10-30",
    "size": "30",
    "color": "Blue",
    "category": "Pants",
    "status": "Will be delivered today",
    "expectedDelivery": "2025-01-21",
    "location": "Lucknow",
    "trackingNumber": "TRK369258147",
    "shippingMethod": "Standard Delivery",
    "orderDate": "2025-01-19",
    "price": 999
  },
  {
    "productId": "11",
    "productName": "Jean Model 11",
    "variantId": "11-34",
    "size": "34",
    "color": "Dark Blue",
    "category": "Jeans",
    "status": "Out for delivery",
    "expectedDelivery": "2025-01-21",
    "location": "Kanpur",
    "trackingNumber": "TRK951753852",
    "shippingMethod": "Express Delivery",
    "orderDate": "2025-01-18",
    "price": 1199
  },
  {
    "productId": "12",
    "productName": "Shirt Model 12",
    "variantId": "12-XL",
    "size": "XL",
    "color": "Gray",
    "category": "Shirts",
    "status": "In transit",
    "expectedDelivery": "2025-01-22",
    "location": "Nagpur",
    "trackingNumber": "TRK753951852",
    "shippingMethod": "Standard Delivery",
    "orderDate": "2025-01-20",
    "price": 1399
  },
  {
    "productId": "13",
    "productName": "Tee Model 13",
    "variantId": "13-M",
    "size": "M",
    "color": "Black",
    "category": "Tees",
    "status": "Order confirmed",
    "expectedDelivery": "2025-01-24",
    "location": "Indore",
    "trackingNumber": "TRK357159753",
    "shippingMethod": "Express Delivery",
    "orderDate": "2025-01-21",
    "price": 899
  },
  {
    "productId": "14",
    "productName": "Pant Model 14",
    "variantId": "14-32",
    "size": "32",
    "color": "Khaki",
    "category": "Pants",
    "status": "Shipped",
    "expectedDelivery": "2025-01-23",
    "location": "Thane",
    "trackingNumber": "TRK159357753",
    "shippingMethod": "Standard Delivery",
    "orderDate": "2025-01-20",
    "price": 1799
  },
  {
    "productId": "15",
    "productName": "Jean Model 15",
    "variantId": "15-30",
    "size": "30",
    "color": "Black",
    "category": "Jeans",
    "status": "Out for delivery",
    "expectedDelivery": "2025-01-21",
    "location": "Bhopal",
    "trackingNumber": "TRK753159357",
    "shippingMethod": "Express Delivery",
    "orderDate": "2025-01-19",
    "price": 999
  }
]